/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NikahStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const NikahRegistration = IDL.Record({
  'id' : IDL.Nat,
  'status' : NikahStatus,
  'brideAadhaarHash' : IDL.Text,
  'city' : IDL.Text,
  'nikahDate' : IDL.Text,
  'qaziName' : IDL.Text,
  'brideName' : IDL.Text,
  'witness1' : IDL.Text,
  'witness2' : IDL.Text,
  'timestamp' : IDL.Int,
  'groomName' : IDL.Text,
  'groomAadhaarHash' : IDL.Text,
  'registeredBy' : IDL.Principal,
  'masjidVenue' : IDL.Text,
});
export const Certificate = IDL.Record({
  'issuedDate' : IDL.Int,
  'nikah' : NikahRegistration,
  'certificateNumber' : IDL.Text,
});
export const JobPosting = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'postedBy' : IDL.Principal,
  'contact' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'timestamp' : IDL.Int,
  'location' : IDL.Text,
});
export const MasjidStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const MasjidProfile = IDL.Record({
  'id' : IDL.Nat,
  'status' : MasjidStatus,
  'city' : IDL.Text,
  'contactPerson' : IDL.Text,
  'registrationNumber' : IDL.Text,
  'email' : IDL.Text,
  'masjidName' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : IDL.Int,
  'facilities' : IDL.Vec(IDL.Text),
  'phone' : IDL.Text,
  'capacity' : IDL.Nat,
  'registeredBy' : IDL.Principal,
});
export const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
export const MatrimonyProposal = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'postedBy' : IDL.Principal,
  'contact' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'education' : IDL.Text,
  'profession' : IDL.Text,
  'description' : IDL.Text,
  'gender' : Gender,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'isMasjid' : IDL.Bool,
  'contact' : IDL.Text,
  'name' : IDL.Text,
});
export const DonationInfo = IDL.Record({
  'upiId' : IDL.Text,
  'qrCodeUrl' : IDL.Text,
});
export const ZakatSettings = IDL.Record({
  'nisabGoldGrams' : IDL.Float64,
  'silverRatePerGram' : IDL.Float64,
  'nisabSilverGrams' : IDL.Float64,
  'goldRatePerGram' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveMasjidRegistration' : IDL.Func([IDL.Nat], [], []),
  'approveNikahRegistration' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateCertificate' : IDL.Func([IDL.Nat], [Certificate], []),
  'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getAllMasjidRegistrations' : IDL.Func(
      [],
      [IDL.Vec(MasjidProfile)],
      ['query'],
    ),
  'getAllMatrimonyProposals' : IDL.Func(
      [],
      [IDL.Vec(MatrimonyProposal)],
      ['query'],
    ),
  'getAllNikahRegistrations' : IDL.Func(
      [],
      [IDL.Vec(NikahRegistration)],
      ['query'],
    ),
  'getApprovedMasjids' : IDL.Func([], [IDL.Vec(MasjidProfile)], ['query']),
  'getCallerMasjidProfile' : IDL.Func([], [IDL.Opt(MasjidProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDonationInfo' : IDL.Func([], [IDL.Opt(DonationInfo)], ['query']),
  'getNikahRegistration' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(NikahRegistration)],
      ['query'],
    ),
  'getPendingMasjidRegistrations' : IDL.Func(
      [],
      [IDL.Vec(MasjidProfile)],
      ['query'],
    ),
  'getPendingNikahRegistrations' : IDL.Func(
      [],
      [IDL.Vec(NikahRegistration)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getZakatSettings' : IDL.Func([], [IDL.Opt(ZakatSettings)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
  'claimAdminIfUnassigned' : IDL.Func([], [IDL.Bool], []),
  'resetAllRolesWithToken' : IDL.Func([IDL.Text], [], []),
  'postJobPosting' : IDL.Func([JobPosting], [IDL.Nat], []),
  'postMatrimonyProposal' : IDL.Func([MatrimonyProposal], [IDL.Nat], []),
  'rejectMasjidRegistration' : IDL.Func([IDL.Nat], [], []),
  'rejectNikahRegistration' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitMasjidRegistration' : IDL.Func([MasjidProfile], [IDL.Nat], []),
  'submitNikahRegistration' : IDL.Func([NikahRegistration], [IDL.Nat], []),
  'updateDonationInfo' : IDL.Func([DonationInfo], [], []),
  'updateZakatSettings' : IDL.Func([ZakatSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NikahStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const NikahRegistration = IDL.Record({
    'id' : IDL.Nat,
    'status' : NikahStatus,
    'brideAadhaarHash' : IDL.Text,
    'city' : IDL.Text,
    'nikahDate' : IDL.Text,
    'qaziName' : IDL.Text,
    'brideName' : IDL.Text,
    'witness1' : IDL.Text,
    'witness2' : IDL.Text,
    'timestamp' : IDL.Int,
    'groomName' : IDL.Text,
    'groomAadhaarHash' : IDL.Text,
    'registeredBy' : IDL.Principal,
    'masjidVenue' : IDL.Text,
  });
  const Certificate = IDL.Record({
    'issuedDate' : IDL.Int,
    'nikah' : NikahRegistration,
    'certificateNumber' : IDL.Text,
  });
  const JobPosting = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'postedBy' : IDL.Principal,
    'contact' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'timestamp' : IDL.Int,
    'location' : IDL.Text,
  });
  const MasjidStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const MasjidProfile = IDL.Record({
    'id' : IDL.Nat,
    'status' : MasjidStatus,
    'city' : IDL.Text,
    'contactPerson' : IDL.Text,
    'registrationNumber' : IDL.Text,
    'email' : IDL.Text,
    'masjidName' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : IDL.Int,
    'facilities' : IDL.Vec(IDL.Text),
    'phone' : IDL.Text,
    'capacity' : IDL.Nat,
    'registeredBy' : IDL.Principal,
  });
  const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
  const MatrimonyProposal = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'postedBy' : IDL.Principal,
    'contact' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'education' : IDL.Text,
    'profession' : IDL.Text,
    'description' : IDL.Text,
    'gender' : Gender,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'isMasjid' : IDL.Bool,
    'contact' : IDL.Text,
    'name' : IDL.Text,
  });
  const DonationInfo = IDL.Record({
    'upiId' : IDL.Text,
    'qrCodeUrl' : IDL.Text,
  });
  const ZakatSettings = IDL.Record({
    'nisabGoldGrams' : IDL.Float64,
    'silverRatePerGram' : IDL.Float64,
    'nisabSilverGrams' : IDL.Float64,
    'goldRatePerGram' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveMasjidRegistration' : IDL.Func([IDL.Nat], [], []),
    'approveNikahRegistration' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateCertificate' : IDL.Func([IDL.Nat], [Certificate], []),
    'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getAllMasjidRegistrations' : IDL.Func(
        [],
        [IDL.Vec(MasjidProfile)],
        ['query'],
      ),
    'getAllMatrimonyProposals' : IDL.Func(
        [],
        [IDL.Vec(MatrimonyProposal)],
        ['query'],
      ),
    'getAllNikahRegistrations' : IDL.Func(
        [],
        [IDL.Vec(NikahRegistration)],
        ['query'],
      ),
    'getApprovedMasjids' : IDL.Func([], [IDL.Vec(MasjidProfile)], ['query']),
    'getCallerMasjidProfile' : IDL.Func(
        [],
        [IDL.Opt(MasjidProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDonationInfo' : IDL.Func([], [IDL.Opt(DonationInfo)], ['query']),
    'getNikahRegistration' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(NikahRegistration)],
        ['query'],
      ),
    'getPendingMasjidRegistrations' : IDL.Func(
        [],
        [IDL.Vec(MasjidProfile)],
        ['query'],
      ),
    'getPendingNikahRegistrations' : IDL.Func(
        [],
        [IDL.Vec(NikahRegistration)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getZakatSettings' : IDL.Func([], [IDL.Opt(ZakatSettings)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
  'claimAdminIfUnassigned' : IDL.Func([], [IDL.Bool], []),
  'resetAllRolesWithToken' : IDL.Func([IDL.Text], [], []),
    'postJobPosting' : IDL.Func([JobPosting], [IDL.Nat], []),
    'postMatrimonyProposal' : IDL.Func([MatrimonyProposal], [IDL.Nat], []),
    'rejectMasjidRegistration' : IDL.Func([IDL.Nat], [], []),
    'rejectNikahRegistration' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitMasjidRegistration' : IDL.Func([MasjidProfile], [IDL.Nat], []),
    'submitNikahRegistration' : IDL.Func([NikahRegistration], [IDL.Nat], []),
    'updateDonationInfo' : IDL.Func([DonationInfo], [], []),
    'updateZakatSettings' : IDL.Func([ZakatSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };