/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Certificate {
  'issuedDate' : bigint,
  'nikah' : NikahRegistration,
  'certificateNumber' : string,
}
export interface DonationInfo { 'upiId' : string, 'qrCodeUrl' : string }
export type Gender = { 'female' : null } |
  { 'male' : null };
export interface JobPosting {
  'id' : bigint,
  'title' : string,
  'postedBy' : Principal,
  'contact' : string,
  'description' : string,
  'company' : string,
  'timestamp' : bigint,
  'location' : string,
}
export interface MasjidProfile {
  'id' : bigint,
  'status' : MasjidStatus,
  'city' : string,
  'contactPerson' : string,
  'registrationNumber' : string,
  'email' : string,
  'masjidName' : string,
  'state' : string,
  'address' : string,
  'timestamp' : bigint,
  'facilities' : Array<string>,
  'phone' : string,
  'capacity' : bigint,
  'registeredBy' : Principal,
}
export type MasjidStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface MatrimonyProposal {
  'id' : bigint,
  'age' : bigint,
  'postedBy' : Principal,
  'contact' : string,
  'city' : string,
  'name' : string,
  'education' : string,
  'profession' : string,
  'description' : string,
  'gender' : Gender,
  'timestamp' : bigint,
}
export interface NikahRegistration {
  'id' : bigint,
  'status' : NikahStatus,
  'brideAadhaarHash' : string,
  'city' : string,
  'nikahDate' : string,
  'qaziName' : string,
  'brideName' : string,
  'witness1' : string,
  'witness2' : string,
  'timestamp' : bigint,
  'groomName' : string,
  'groomAadhaarHash' : string,
  'registeredBy' : Principal,
  'masjidVenue' : string,
}
export type NikahStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface UserProfile {
  'isMasjid' : boolean,
  'contact' : string,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ZakatSettings {
  'nisabGoldGrams' : number,
  'silverRatePerGram' : number,
  'nisabSilverGrams' : number,
  'goldRatePerGram' : number,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveMasjidRegistration' : ActorMethod<[bigint], undefined>,
  'approveNikahRegistration' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateCertificate' : ActorMethod<[bigint], Certificate>,
  'getAllJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getAllMasjidRegistrations' : ActorMethod<[], Array<MasjidProfile>>,
  'getAllMatrimonyProposals' : ActorMethod<[], Array<MatrimonyProposal>>,
  'getAllNikahRegistrations' : ActorMethod<[], Array<NikahRegistration>>,
  'getApprovedMasjids' : ActorMethod<[], Array<MasjidProfile>>,
  'getCallerMasjidProfile' : ActorMethod<[], [] | [MasjidProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDonationInfo' : ActorMethod<[], [] | [DonationInfo]>,
  'getNikahRegistration' : ActorMethod<[bigint], [] | [NikahRegistration]>,
  'getPendingMasjidRegistrations' : ActorMethod<[], Array<MasjidProfile>>,
  'getPendingNikahRegistrations' : ActorMethod<[], Array<NikahRegistration>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getZakatSettings' : ActorMethod<[], [] | [ZakatSettings]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postJobPosting' : ActorMethod<[JobPosting], bigint>,
  'postMatrimonyProposal' : ActorMethod<[MatrimonyProposal], bigint>,
  'rejectMasjidRegistration' : ActorMethod<[bigint], undefined>,
  'rejectNikahRegistration' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitMasjidRegistration' : ActorMethod<[MasjidProfile], bigint>,
  'submitNikahRegistration' : ActorMethod<[NikahRegistration], bigint>,
  'updateDonationInfo' : ActorMethod<[DonationInfo], undefined>,
  'updateZakatSettings' : ActorMethod<[ZakatSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];