/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DonationInfo {
    upiId: string;
    qrCodeUrl: string;
}
export interface ZakatSettings {
    nisabGoldGrams: number;
    silverRatePerGram: number;
    nisabSilverGrams: number;
    goldRatePerGram: number;
}
export interface MatrimonyProposal {
    id: bigint;
    age: bigint;
    postedBy: Principal;
    contact: string;
    city: string;
    name: string;
    education: string;
    profession: string;
    description: string;
    gender: Gender;
    timestamp: bigint;
}
export interface NikahRegistration {
    id: bigint;
    status: NikahStatus;
    brideAadhaarHash: string;
    city: string;
    nikahDate: string;
    qaziName: string;
    brideName: string;
    witness1: string;
    witness2: string;
    timestamp: bigint;
    groomName: string;
    groomAadhaarHash: string;
    registeredBy: Principal;
    masjidVenue: string;
}
export interface JobPosting {
    id: bigint;
    title: string;
    postedBy: Principal;
    contact: string;
    description: string;
    company: string;
    timestamp: bigint;
    location: string;
}
export interface Certificate {
    issuedDate: bigint;
    nikah: NikahRegistration;
    certificateNumber: string;
}
export interface UserProfile {
    isMasjid: boolean;
    contact: string;
    name: string;
}
export interface MasjidProfile {
    id: bigint;
    status: MasjidStatus;
    city: string;
    contactPerson: string;
    registrationNumber: string;
    email: string;
    masjidName: string;
    state: string;
    address: string;
    timestamp: bigint;
    facilities: Array<string>;
    phone: string;
    capacity: bigint;
    registeredBy: Principal;
}
export enum Gender {
    female = "female",
    male = "male"
}
export enum NikahStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface ZakatProfile {
    id: bigint;
    masjidId: bigint;
    personName: string;
    story: string;
    requiredAmount: number;
    collectedAmount: number;
    upiId: string;
    status: ZakatProfileStatus;
    createdBy: Principal;
    timestamp: bigint;
}
export enum MasjidStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum ZakatProfileStatus {
    open = "open",
    fulfilled = "fulfilled",
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveMasjidRegistration(id: bigint): Promise<void>;
    approveNikahRegistration(id: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    generateCertificate(nikahId: bigint): Promise<Certificate>;
    getAllJobPostings(): Promise<Array<JobPosting>>;
    getAllMasjidRegistrations(): Promise<Array<MasjidProfile>>;
    getAllMatrimonyProposals(): Promise<Array<MatrimonyProposal>>;
    getAllNikahRegistrations(): Promise<Array<NikahRegistration>>;
    getApprovedMasjids(): Promise<Array<MasjidProfile>>;
    getCallerMasjidProfile(): Promise<MasjidProfile | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDonationInfo(): Promise<DonationInfo | null>;
    getNikahRegistration(id: bigint): Promise<NikahRegistration | null>;
    getPendingMasjidRegistrations(): Promise<Array<MasjidProfile>>;
    getPendingNikahRegistrations(): Promise<Array<NikahRegistration>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getZakatSettings(): Promise<ZakatSettings | null>;
    isCallerAdmin(): Promise<boolean>;
    postJobPosting(job: JobPosting): Promise<bigint>;
    postMatrimonyProposal(proposal: MatrimonyProposal): Promise<bigint>;
    rejectMasjidRegistration(id: bigint): Promise<void>;
    rejectNikahRegistration(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitMasjidRegistration(profile: MasjidProfile): Promise<bigint>;
    submitNikahRegistration(registration: NikahRegistration): Promise<bigint>;
    updateDonationInfo(info: DonationInfo): Promise<void>;
    updateZakatSettings(settings: ZakatSettings): Promise<void>;
}
import type { Certificate as _Certificate, DonationInfo as _DonationInfo, Gender as _Gender, MasjidProfile as _MasjidProfile, MasjidStatus as _MasjidStatus, MatrimonyProposal as _MatrimonyProposal, NikahRegistration as _NikahRegistration, NikahStatus as _NikahStatus, UserProfile as _UserProfile, UserRole as _UserRole, ZakatSettings as _ZakatSettings } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveMasjidRegistration(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveMasjidRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveMasjidRegistration(arg0);
            return result;
        }
    }
    async approveNikahRegistration(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveNikahRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveNikahRegistration(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async generateCertificate(arg0: bigint): Promise<Certificate> {
        if (this.processError) {
            try {
                const result = await this.actor.generateCertificate(arg0);
                return from_candid_Certificate_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateCertificate(arg0);
            return from_candid_Certificate_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllJobPostings(): Promise<Array<JobPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobPostings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobPostings();
            return result;
        }
    }
    async getAllMasjidRegistrations(): Promise<Array<MasjidProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMasjidRegistrations();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMasjidRegistrations();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMatrimonyProposals(): Promise<Array<MatrimonyProposal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatrimonyProposals();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatrimonyProposals();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNikahRegistrations(): Promise<Array<NikahRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNikahRegistrations();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNikahRegistrations();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovedMasjids(): Promise<Array<MasjidProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedMasjids();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedMasjids();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerMasjidProfile(): Promise<MasjidProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerMasjidProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerMasjidProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonationInfo(): Promise<DonationInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonationInfo();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonationInfo();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNikahRegistration(arg0: bigint): Promise<NikahRegistration | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNikahRegistration(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNikahRegistration(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingMasjidRegistrations(): Promise<Array<MasjidProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingMasjidRegistrations();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingMasjidRegistrations();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingNikahRegistrations(): Promise<Array<NikahRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingNikahRegistrations();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingNikahRegistrations();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getZakatSettings(): Promise<ZakatSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getZakatSettings();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getZakatSettings();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async postJobPosting(arg0: JobPosting): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.postJobPosting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postJobPosting(arg0);
            return result;
        }
    }
    async postMatrimonyProposal(arg0: MatrimonyProposal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.postMatrimonyProposal(to_candid_MatrimonyProposal_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postMatrimonyProposal(to_candid_MatrimonyProposal_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async rejectMasjidRegistration(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectMasjidRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectMasjidRegistration(arg0);
            return result;
        }
    }
    async rejectNikahRegistration(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectNikahRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectNikahRegistration(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitMasjidRegistration(arg0: MasjidProfile): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMasjidRegistration(to_candid_MasjidProfile_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMasjidRegistration(to_candid_MasjidProfile_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitNikahRegistration(arg0: NikahRegistration): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitNikahRegistration(to_candid_NikahRegistration_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitNikahRegistration(to_candid_NikahRegistration_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDonationInfo(arg0: DonationInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDonationInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDonationInfo(arg0);
            return result;
        }
    }
    async updateZakatSettings(arg0: ZakatSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateZakatSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateZakatSettings(arg0);
            return result;
        }
    }

    async adminDeleteMasjidRegistration(arg0: bigint): Promise<void> {
        const result = await this.actor.adminDeleteMasjidRegistration(arg0);
        return result;
    }
    async adminDeleteNikahRegistration(arg0: bigint): Promise<void> {
        const result = await this.actor.adminDeleteNikahRegistration(arg0);
        return result;
    }
    async adminUpdateNikahRegistration(arg0: bigint, arg1: NikahRegistration): Promise<void> {
        const result = await this.actor.adminUpdateNikahRegistration(arg0, to_candid_NikahRegistration_n34(this._uploadFile, this._downloadFile, arg1));
        return result;
    }
    async adminDeleteMatrimonyProposal(arg0: bigint): Promise<void> {
        const result = await this.actor.adminDeleteMatrimonyProposal(arg0);
        return result;
    }
    async adminUpdateMatrimonyProposal(arg0: bigint, arg1: MatrimonyProposal): Promise<void> {
        const result = await this.actor.adminUpdateMatrimonyProposal(arg0, to_candid_MatrimonyProposal_n26(this._uploadFile, this._downloadFile, arg1));
        return result;
    }
    async adminDeleteJobPosting(arg0: bigint): Promise<void> {
        const result = await this.actor.adminDeleteJobPosting(arg0);
        return result;
    }
    async adminUpdateJobPosting(arg0: bigint, arg1: JobPosting): Promise<void> {
        const result = await this.actor.adminUpdateJobPosting(arg0, arg1);
        return result;
    }
    async getCallerNikahRegistrations(): Promise<Array<NikahRegistration>> {
        const result = await this.actor.getCallerNikahRegistrations();
        return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
    }
    async getCallerMatrimonyProposals(): Promise<Array<MatrimonyProposal>> {
        const result = await this.actor.getCallerMatrimonyProposals();
        return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
    }
    async getCallerJobPostings(): Promise<Array<JobPosting>> {
        const result = await this.actor.getCallerJobPostings();
        return result;
    }
    async getAllZakatProfiles(): Promise<Array<ZakatProfile>> {
        const result = await (this.actor as any).getAllZakatProfiles();
        return result;
    }
    async createZakatProfile(arg0: ZakatProfile): Promise<bigint> {
        const result = await (this.actor as any).createZakatProfile(arg0);
        return result;
    }
    async updateZakatProfile(arg0: bigint, arg1: ZakatProfile): Promise<void> {
        const result = await (this.actor as any).updateZakatProfile(arg0, arg1);
        return result;
    }
    async deleteZakatProfile(arg0: bigint): Promise<void> {
        const result = await (this.actor as any).deleteZakatProfile(arg0);
        return result;
    }
    async markZakatProfileFulfilled(arg0: bigint): Promise<void> {
        const result = await (this.actor as any).markZakatProfileFulfilled(arg0);
        return result;
    }
    async updateZakatCollectedAmount(arg0: bigint, arg1: number): Promise<void> {
        const result = await (this.actor as any).updateZakatCollectedAmount(arg0, arg1);
        return result;
    }
    async adminUpdateMasjidProfile(arg0: bigint, arg1: MasjidProfile): Promise<void> {
        const result = await this.actor.adminUpdateMasjidProfile(arg0, to_candid_MasjidProfile_n30(this._uploadFile, this._downloadFile, arg1));
        return result;
    }
    async getZakatProfilesByMasjid(arg0: bigint): Promise<Array<ZakatProfile>> {
        const result = await (this.actor as any).getZakatProfilesByMasjid(arg0);
        return result;
    }
    async getOpenZakatProfiles(): Promise<Array<ZakatProfile>> {
        const result = await (this.actor as any).getOpenZakatProfiles();
        return result;
    }
    async isAdminAssigned(): Promise<boolean> {
        const result = await this.actor.isAdminAssigned();
        return result;
    }
    async claimAdminIfUnassigned(): Promise<boolean> {
        const result = await this.actor.claimAdminIfUnassigned();
        return result;
    }
    async resetAllRolesWithToken(arg0: string): Promise<void> {
        const result = await this.actor.resetAllRolesWithToken(arg0);
        return result;
    }

}
function from_candid_Certificate_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Certificate): Certificate {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_MasjidProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MasjidProfile): MasjidProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_MasjidStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MasjidStatus): MasjidStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_MatrimonyProposal_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatrimonyProposal): MatrimonyProposal {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_NikahRegistration_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NikahRegistration): NikahRegistration {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_NikahStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NikahStatus): NikahStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MasjidProfile]): MasjidProfile | null {
    return value.length === 0 ? null : from_candid_MasjidProfile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DonationInfo]): DonationInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NikahRegistration]): NikahRegistration | null {
    return value.length === 0 ? null : from_candid_NikahRegistration_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ZakatSettings]): ZakatSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _MasjidStatus;
    city: string;
    contactPerson: string;
    registrationNumber: string;
    email: string;
    masjidName: string;
    state: string;
    address: string;
    timestamp: bigint;
    facilities: Array<string>;
    phone: string;
    capacity: bigint;
    registeredBy: Principal;
}): {
    id: bigint;
    status: MasjidStatus;
    city: string;
    contactPerson: string;
    registrationNumber: string;
    email: string;
    masjidName: string;
    state: string;
    address: string;
    timestamp: bigint;
    facilities: Array<string>;
    phone: string;
    capacity: bigint;
    registeredBy: Principal;
} {
    return {
        id: value.id,
        status: from_candid_MasjidStatus_n12(_uploadFile, _downloadFile, value.status),
        city: value.city,
        contactPerson: value.contactPerson,
        registrationNumber: value.registrationNumber,
        email: value.email,
        masjidName: value.masjidName,
        state: value.state,
        address: value.address,
        timestamp: value.timestamp,
        facilities: value.facilities,
        phone: value.phone,
        capacity: value.capacity,
        registeredBy: value.registeredBy
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    age: bigint;
    postedBy: Principal;
    contact: string;
    city: string;
    name: string;
    education: string;
    profession: string;
    description: string;
    gender: _Gender;
    timestamp: bigint;
}): {
    id: bigint;
    age: bigint;
    postedBy: Principal;
    contact: string;
    city: string;
    name: string;
    education: string;
    profession: string;
    description: string;
    gender: Gender;
    timestamp: bigint;
} {
    return {
        id: value.id,
        age: value.age,
        postedBy: value.postedBy,
        contact: value.contact,
        city: value.city,
        name: value.name,
        education: value.education,
        profession: value.profession,
        description: value.description,
        gender: from_candid_Gender_n16(_uploadFile, _downloadFile, value.gender),
        timestamp: value.timestamp
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    issuedDate: bigint;
    nikah: _NikahRegistration;
    certificateNumber: string;
}): {
    issuedDate: bigint;
    nikah: NikahRegistration;
    certificateNumber: string;
} {
    return {
        issuedDate: value.issuedDate,
        nikah: from_candid_NikahRegistration_n5(_uploadFile, _downloadFile, value.nikah),
        certificateNumber: value.certificateNumber
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _NikahStatus;
    brideAadhaarHash: string;
    city: string;
    nikahDate: string;
    qaziName: string;
    brideName: string;
    witness1: string;
    witness2: string;
    timestamp: bigint;
    groomName: string;
    groomAadhaarHash: string;
    registeredBy: Principal;
    masjidVenue: string;
}): {
    id: bigint;
    status: NikahStatus;
    brideAadhaarHash: string;
    city: string;
    nikahDate: string;
    qaziName: string;
    brideName: string;
    witness1: string;
    witness2: string;
    timestamp: bigint;
    groomName: string;
    groomAadhaarHash: string;
    registeredBy: Principal;
    masjidVenue: string;
} {
    return {
        id: value.id,
        status: from_candid_NikahStatus_n7(_uploadFile, _downloadFile, value.status),
        brideAadhaarHash: value.brideAadhaarHash,
        city: value.city,
        nikahDate: value.nikahDate,
        qaziName: value.qaziName,
        brideName: value.brideName,
        witness1: value.witness1,
        witness2: value.witness2,
        timestamp: value.timestamp,
        groomName: value.groomName,
        groomAadhaarHash: value.groomAadhaarHash,
        registeredBy: value.registeredBy,
        masjidVenue: value.masjidVenue
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
}): Gender {
    return "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): NikahStatus {
    return "pending" in value ? NikahStatus.pending : "approved" in value ? NikahStatus.approved : "rejected" in value ? NikahStatus.rejected : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MatrimonyProposal>): Array<MatrimonyProposal> {
    return value.map((x)=>from_candid_MatrimonyProposal_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NikahRegistration>): Array<NikahRegistration> {
    return value.map((x)=>from_candid_NikahRegistration_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MasjidProfile>): Array<MasjidProfile> {
    return value.map((x)=>from_candid_MasjidProfile_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Gender_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_MasjidProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MasjidProfile): _MasjidProfile {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_MasjidStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MasjidStatus): _MasjidStatus {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_MatrimonyProposal_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatrimonyProposal): _MatrimonyProposal {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_NikahRegistration_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NikahRegistration): _NikahRegistration {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_NikahStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NikahStatus): _NikahStatus {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    age: bigint;
    postedBy: Principal;
    contact: string;
    city: string;
    name: string;
    education: string;
    profession: string;
    description: string;
    gender: Gender;
    timestamp: bigint;
}): {
    id: bigint;
    age: bigint;
    postedBy: Principal;
    contact: string;
    city: string;
    name: string;
    education: string;
    profession: string;
    description: string;
    gender: _Gender;
    timestamp: bigint;
} {
    return {
        id: value.id,
        age: value.age,
        postedBy: value.postedBy,
        contact: value.contact,
        city: value.city,
        name: value.name,
        education: value.education,
        profession: value.profession,
        description: value.description,
        gender: to_candid_Gender_n28(_uploadFile, _downloadFile, value.gender),
        timestamp: value.timestamp
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: MasjidStatus;
    city: string;
    contactPerson: string;
    registrationNumber: string;
    email: string;
    masjidName: string;
    state: string;
    address: string;
    timestamp: bigint;
    facilities: Array<string>;
    phone: string;
    capacity: bigint;
    registeredBy: Principal;
}): {
    id: bigint;
    status: _MasjidStatus;
    city: string;
    contactPerson: string;
    registrationNumber: string;
    email: string;
    masjidName: string;
    state: string;
    address: string;
    timestamp: bigint;
    facilities: Array<string>;
    phone: string;
    capacity: bigint;
    registeredBy: Principal;
} {
    return {
        id: value.id,
        status: to_candid_MasjidStatus_n32(_uploadFile, _downloadFile, value.status),
        city: value.city,
        contactPerson: value.contactPerson,
        registrationNumber: value.registrationNumber,
        email: value.email,
        masjidName: value.masjidName,
        state: value.state,
        address: value.address,
        timestamp: value.timestamp,
        facilities: value.facilities,
        phone: value.phone,
        capacity: value.capacity,
        registeredBy: value.registeredBy
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: NikahStatus;
    brideAadhaarHash: string;
    city: string;
    nikahDate: string;
    qaziName: string;
    brideName: string;
    witness1: string;
    witness2: string;
    timestamp: bigint;
    groomName: string;
    groomAadhaarHash: string;
    registeredBy: Principal;
    masjidVenue: string;
}): {
    id: bigint;
    status: _NikahStatus;
    brideAadhaarHash: string;
    city: string;
    nikahDate: string;
    qaziName: string;
    brideName: string;
    witness1: string;
    witness2: string;
    timestamp: bigint;
    groomName: string;
    groomAadhaarHash: string;
    registeredBy: Principal;
    masjidVenue: string;
} {
    return {
        id: value.id,
        status: to_candid_NikahStatus_n36(_uploadFile, _downloadFile, value.status),
        brideAadhaarHash: value.brideAadhaarHash,
        city: value.city,
        nikahDate: value.nikahDate,
        qaziName: value.qaziName,
        brideName: value.brideName,
        witness1: value.witness1,
        witness2: value.witness2,
        timestamp: value.timestamp,
        groomName: value.groomName,
        groomAadhaarHash: value.groomAadhaarHash,
        registeredBy: value.registeredBy,
        masjidVenue: value.masjidVenue
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    female: null;
} | {
    male: null;
} {
    return value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NikahStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == NikahStatus.pending ? {
        pending: null
    } : value == NikahStatus.approved ? {
        approved: null
    } : value == NikahStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
